image:
  file: .gitpod.Dockerfile

tasks:
  - name: run post-start script
    command: bash .gitpod.post_create.sh

vscode:
  extensions:
    - ms-python.vscode-pylance
    - mtxr.sqltools
    - mtxr.mtxr.sqltools-driver-mysql
    - streetsidesoftware.code-spell-checker
    - bungcip.better-toml
