version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db

  db:
    image: mysql/mysql-server:8.0.23
    container_name: db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: task_management
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_user_password
    ports:
      - 3306:3306

  nginx:
    image: nginx:1.19.5-alpine
    container_name: nginx
    volumes:
      - ./task_management_system_nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app
    command: ["nginx", "-g", "daemon off;"]

volumes:
  db_data:
