version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    #  networks:
    #   - my-network
    depends_on:
      - db

  db:
    image: mysql/mysql-server:8.0.23
    container_name: db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: task_management
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_user_password
    # networks:
    #   - my-network
    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MySQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    # ports:
    #   - 3306:3306

  nginx:
    image: nginx:1.19.5-alpine
    container_name: nginx
    volumes:
      - ./task_management_system_nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app
    command: ["nginx", "-g", "daemon off;"]
    # networks:
    #   - my-network


volumes:
  db_data:

# networks:
#   my-network:
